<?php
include 'Template/layout/header.phtml';
?>

<form action="<?=BASE_URL?>updateProduct" method="POST">
<input type="hidden" name="id_producto" value="<?php echo $row['id_producto']; ?>">
<input type="text" name="Nombre_producto" id="Nombre_producto" value="<?php echo $row['Nombre_producto']; ?>" >
<input type="text" name="id_proveedor_fk" id="id_proveedor_fk" value="<?php echo $row['id_proveedor_fk']; ?>" >
<input type="text" name="categoria" id="categoria" value="<?php echo $row['categoria']; ?>" >
<input type="text" name="cantidad" id="cantidad" value="<?php echo $row['cantidad']; ?>" >
<input type="text" name="talle" id="talle" value="<?php echo $row['talle']; ?>" >
<input type="text" name="valor" id="valor" value="<?php echo $row['valor']; ?>" >
<input type="submit" value="Actualizar producto">
</form>


<?php
include 'Template/layout/footer.phtml';
?>


