<?php include 'Template/layout/header.phtml'; ?> 
<h1>Detalle del Producto</h1>
<a href='router.php?action=home'>Volver</a>"; 
<p>Nombre: <?= htmlspecialchars($product->Nombre_producto) ?></p>
<p>Categoría: <?= htmlspecialchars($product->categoria) ?></p>
<p>Cantidad: <?= htmlspecialchars($product->cantidad) ?></p>
<p>Talle: <?= htmlspecialchars($product->talle) ?></p>
<p>Valor: <?= htmlspecialchars($product->valor) ?></p>
<?php include 'Template/layout/footer.phtml'; ?> 