<?php include 'Template/layout/header.phtml';?>

<div class="login-container">

    <?php if ($error): ?>
        <div class="error-message" style="color: red; margin-bottom: 10px;">
            <?php echo htmlspecialchars($error); // Escapar el mensaje para seguridad ?>
        </div>
    <?php endif; ?>
<form method="post" action="Login">
        <div class="form-group">
            <label for="username">Usuario</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="form-group">
            <label for="password">Contraseña</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <button type="submit" class="btn btn-primary">Iniciar sesión</button>
    </form>
</div>
<?php include 'Template/layout/footer.phtml';?>
