<?php include 'Template/layout/header.phtml'; ?> 

<h1>Productos del Proveedor</h1>
<a href='router.php?action=home'>Volver</a>
<?php if (!empty($products) && is_array($products)): ?>
    <ul>
        <?php foreach ($products as $product): ?>
            Nombre: <?= htmlspecialchars($product->Nombre_producto) ?>
            <li>Categoría: <?= htmlspecialchars($product->categoria) ?></li>
            <li>Cantidad: <?= htmlspecialchars($product->cantidad) ?></li>
            <li>Talle: <?= htmlspecialchars($product->talle) ?></li>
            <li>Valor: <?= htmlspecialchars($product->valor) ?></li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p>No hay productos para este proveedor.</p>
<?php endif; ?>
<?php include 'Template/layout/footer.phtml'; ?> 
